### ISSUE TITLE
The `add` command should sort `package.metadata.cargo-compete.bin`

### ISSUE THREAD

**Issue by qryxip** [qryxip/cargo-compete#118]
今の仕様だと単にappendするだけなので適切な場所に挿入するか，末尾に追加したあとにソートする．

```toml
[package.metadata.cargo-compete.bin]
9001 = {problem = "https://yukicoder.me/problems/no/9001"}
1358 = {problem = "https://yukicoder.me/problems/no/1358"}
1359 = {problem = "https://yukicoder.me/problems/no/1359"}
1360 = {problem = "https://yukicoder.me/problems/no/1360"}
1361 = {problem = "https://yukicoder.me/problems/no/1361"}
1362 = {problem = "https://yukicoder.me/problems/no/1362"}
1363 = {problem = "https://yukicoder.me/problems/no/1363"}
1364 = {problem = "https://yukicoder.me/problems/no/1364"}
1365 = {problem = "https://yukicoder.me/problems/no/1365"}
```
