### ISSUE TITLE
Add an option that creates one package for the `init` command, and remove the `new` function for yukicoder

### ISSUE THREAD

**Issue by qryxip** [qryxip/cargo-compete#119]
yukicoder(やLibrary Checker)用には`init`時にこのようなパッケージを作り，コンテストに参加するときは`add`コマンドを使ってもらう．

```console
.
├── Cargo.lock
├── compete.toml
├── rust-toolchain
└── src
    └── bin
        └── dummy.rs
```

```toml
[package.metadata.cargo-compete.bin]
dummy = { problem = "https://example.com" }
```

- [ ] `compete.toml`の`new.template`をどこかに移動
- [ ] `compete.toml`の`new`をoptionalに
