### ISSUE TITLE
For "AtCoder Rules against Generative AI ver20240607"

### ISSUE THREAD

**Issue by qryxip** [qryxip/cargo-compete#214]
[AtCoder Rules against Generative AI ver20240607](https://info.atcoder.jp/entry/llm-abc-rules-en)
[AtCoder生成AI対策ルール - 20240607版](https://info.atcoder.jp/entry/llm-abc-rules-ja)

cargo-compete extracts time limits and relative/absolute errors. They are not "specific integers or strings"/"固有の整数や固有名詞などの文字列".

```yaml
---
type: Batch
timelimit: 2s
#          ^^
match:
  Float:
    relative_error: 1e-8
    #               ^^^^
    absolute_error: 1e-8
    #               ^^^^
```
