### ISSUE TITLE
Add `new.template.profile`

### ISSUE THREAD

**Issue by qryxip** [qryxip/cargo-compete#75]
`profile`を書くことで`debug-assertions`と`overflow-checks`を有効にしたままTLEしない程度の`opt-level`を設定できる。しかし現在、設定ファイルにはこれに対応する項目が無い。

```toml
[profile.dev]
opt-level = 2
```
