### ISSUE TITLE
Simplify `package.metadata.cargo-compete.bin.*.problem`

### ISSUE THREAD

**Issue by qryxip** [qryxip/cargo-compete#92]
URLだけで問題を識別するようにする。ojが長年これで上手くいってるしURL単体からでもコンテストのIDは取れるはず。

```toml
[package.metadata.cargo-compete.bin]
a = { name = "practice-a", problem = "https://atcoder.jp/contests/practice/tasks/practice_1" }
b = { name = "practice-b", problem = "https://atcoder.jp/contests/practice/tasks/practice_2" }
```
